(function(scope) {
  const cellData = [
    {
      name: 'VASCULAR PLANT',
      jpname: '管状花冠の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/UDWuDipgTPwrHsEbxHaP.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/pNXGOrmpVtcMEiKPKaEV.png',
      color: '#cbbad9',
    },
    {
      name: 'KIDNEY BEAN SECTIONAL',
      jpname: 'インゲン豆類の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/rZLJVYvUCzxZweixqMBf.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/CMowApoPGRaSawETkMZw.png',
      color: '#9dadd7',
    },
    {
      name: 'OAK TREE STEM',
      jpname: 'オークの枝',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/yKgOZZikntRsxpPnYNTD.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/ohPdiqmWnNWRuEqvFRzT.png',
      color: '#c24449',
    },
    {
      name: 'NERVE FIBER BUNDLE',
      jpname: '神経糸球体',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/fbFZKkuUcUEFZuzemPaz.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/spSLXlzWmIDfVmDgURWL.png',
      color: '#d86681',
    },
    {
      name: 'ASCARIS LUMBRICOIDES',
      jpname: '回虫の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/ZGsVsYrzANsZIXCaxHlB.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/xgrhzThKowlKnPMAffUR.png',
      color: '#af6148',
    },
    {
      name: 'BONE MARROW SECTIONAL',
      jpname: '骨髄の中心断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/oXHDWFvgNadxdjdKNuzh.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/dvFPZTuVXICZnmUSIGAL.png',
      color: '#743c4d',
    },
    {
      name: 'NERVE CELL NEURON',
      jpname: '神経の細胞組織',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/MSqZRyrdqTdjbXUYZGRV.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/HpfmXQwxrxzynqALJBwX.png',
      color: '#395c84',
    },
    {
      name: 'ESCHERICHIA EPEC',
      jpname: '大腸菌の細胞二元分裂',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/OaUqZSTIULfDXgXLdNSJ.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/bmyVnRMifzeCeZxtEwMF.png',
      color: '#45a07e',
    },
    {
      name: 'THE IRIS ROOT',
      jpname: 'アヤメ根',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/BwAmiAMuiDnRMbpnvaoM.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/gUiqhbcKHJCxHrMkTLus.png',
      color: '#88b5a3',
    },
    {
      name: 'LOTUS STEM LEAF',
      jpname: '蓮華の葉気泡組織',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/QxWeeYpzIlVvrUVszXdm.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/MXWZZWkLQriDLxxZyGEK.png',
      color: '#93cfcb',
    },
    {
      name: 'DRAGON TREE STEM',
      jpname: '竜血樹の組織茎の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/ArZEhBxCKontWdLjGhfV.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/OBvgkNWqnbozGwToKBKZ.png',
      color: '#3ab2db',
    },
    {
      name: 'ASPARAGUS PULPA',
      jpname: 'アロエ多肉植物の細胞',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/EAuteenxxkSiAKKIWdyK.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/SSSWnwSDiwXntZGOfQdb.png',
      color: '#bdcca5',
    },
    {
      name: 'PLANT CELL VEGETABLE',
      jpname: '野菜の茎',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/CcXWuTQmFJaRySYUWGfA.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/GyeCpCbUveJGIpIcVkAb.png',
      color: '#abc79f',
    },
    {
      name: 'ROSACEAE STEM LEAF',
      jpname: '薔薇科の低木茎の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/zdiAXarZEIfIVQVmipaL.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/XGfrWwWUuoxlphirIuWR.png',
      color: '#b6d1a9',
    },
    {
      name: 'CARROT SECTIONAL',
      jpname: '人参の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/dlAwMvkZysJgUrdlIMvw.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/BKNJrmJhEfGwQbNDUaFU.png',
      color: '#ddba8c',
    },
    {
      name: 'YEW TREE STEM',
      jpname: 'あららぎの茎の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/pXvrtjWBVMcPlxEPagDy.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/ngAVDdcqEGKhCrnYeLmB.png',
      color: '#e0ce97',
    },
    {
      name: 'INFLUENZA VIRUS',
      jpname: 'インフルエンザ',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/ScUrIHZGhroBqwyAOzjd.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/TjuUXJDGYAAKEnhMmYPn.png',
      color: '#e68544',
    },
    {
      name: 'ESOPHAGUS SECTIONAL',
      jpname: '食道の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/iWJHtXHhPcPjeqnfSJSB.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/sSdTAQoKLqfaFhViCGUN.png',
      color: '#e5c826',
    },
    {
      name: 'FIBROUS ASTROCYTE',
      jpname: '星状胶状細胞',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/ncxOSXKEUsZfNtFCgeFm.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/bjBCYzrdRWphiGpElBek.png',
      color: '#e9d0d5',
    },
    {
      name: 'MUSCLE TISSUE',
      jpname: '筋肉の組織の簡略化',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/XDXqmIULItClVdsaLUHz.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/vlSJisDPBPdRZSNqGSdC.png',
      color: '#dec8c6',
    },
    {
      name: 'RABIES VIRUS',
      jpname: '狂犬病の病毒i',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/cFPKMcuGCxJgKxNDmNRJ.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/DxraqOtlzqCBFQhpTBxO.png',
      color: '#eedbe1',
    },
    {
      name: 'RADISH BUD SECTIONAL',
      jpname: '蘿蔔の蕾の断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/OCXuPmVppjtRsuAwtVjE.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/AIirRGAhjYnUoafRkxUo.png',
      color: '#dcdfe0',
    },
    {
      name: 'COLI GROUP COLIFORM',
      jpname: '大腸菌の細胞',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/bFvROqcoVdAyXmDBTIWr.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/ELkrsdAfpavRPIWksWWy.png',
      color: '#d8dad1',
    },
    {
      name: 'RENAL CELL CARCINOMA',
      jpname: '腎癌の癌細胞点状細胞',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/OusnXRJySZFYEPmgwmbc.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/LKfEHTdriBWVESEXOBcU.png',
      color: '#e4e6e3',
    },
    {
      name: 'HEREDITARY ELLIPTOCYTOSIS',
      jpname: '遺伝性の細胞楕円形赤血球',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/DVhshdkxtEYephkGweUd.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/MwjyqThaWSBEaLbKYnjP.png',
      color: '#6bbecb',
    },
    {
      name: 'ROOT FUNGUS FUNGI',
      jpname: '真菌根断面図',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/euQqbjfCTApPXIIqBlvO.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/NlUoHOrJNLXQxBiximet.png',
      color: '#ebc85d',
    },

    {
      name: 'MICRASTERIAS CRUX MELITENSIS',
      jpname: 'ミラステリアス トビムシ',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/MifLvTpMILHuXEOMLXjp.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/ewdwJDnKgbigisnheTAW.png',
      color: '#d7e8cc',
    },
    {
      name: 'DIATOM',
      jpname: '珪藻',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/hCwsEmvdzLqKcdKHjaSn.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/xtzGrKlvUPBjzfgfWoJx.png',
      color: '#dab3b4',
    },
    {
      name: 'HEUCHERA TRICHOMES',
      jpname: 'ハイチュラ トリムホームズ',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/HbxgxxXTqzvYIxewufSL.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/AxfXlkGDWRuAWffpJpsp.png',
      color: '#748bb5',
    },
    {
      name: 'LILY VALLEY STOMATA',
      jpname: 'リリの気孔',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/VFUdySiLAKWFPeREqXZS.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/EPxiOkwhsKJZSMIFsTci.png',
      color: '#bcbdb8',
    },
    {
      name: 'WINTER JASMIN',
      jpname: '冬のジャスミン',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/LmpecgKzpQqizXgrqhzY.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/aKVgyMfyAFiBhMqNurDA.png',
      color: '#eaeae1',
    },
    {
      name: 'COSCINODISCUS DIATOM',
      jpname: 'コシノディスカス 珪藻',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/lYjxWkLgyNbZaVClvCEA.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/UXLfEhkeRuGWHNHIbpBj.png',
      color: '#f7f0c7',
    },
    {
      name: 'MYCOPLASMA GENITALIUM',
      jpname: '生殖支原体',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/SEngyVwOEEZDaNIguhuJ.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/yRslaqXhgHjzdfbcAfSm.png',
      color: '#abc097',
    },
    {
      name: 'BUTTERCUP STEM',
      jpname: '金鳳花の茎',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/ZCmXxQDeTiyAgQVhlsiQ.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/yUdfSzaEttHNCnUwxtoa.png',
      color: '#a86f7f',
    },
    {
      name: 'OHIA LEHUA TREE LEAF STOMATA',
      jpname: '桃金娘花の気孔',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/ptfdVltuLgAgAxFMLKHX.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/pvbknQiYyTMiiwLJyKHz.png',
      color: '#afe9eb',
    },
    {
      name: 'PINE POLLEN GRAINS',
      jpname: '松の花粉',
      image: 'https://gw.alipayobjects.com/zos/rmsportal/VMIXAxXPqrhxwkNePrWE.png',
      icon: 'https://gw.alipayobjects.com/zos/rmsportal/lHjxtdMqDOQpYMBHzNuE.png',
      color: '#a8ac74',
    },
  ];
  scope.cellData = cellData;
})(window);